config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  root to: "home#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :home, only: [:index]

  resources :pages, only: [:index, :show, :new, :create, :edit, :update] do

  end
  resources :houses, only: [:index, :show, :new, :create, :edit, :update] do
    resources :house_ingredients do
      collection do
        #ajout de cet élément pour crééer une route path
        post :analyze_ticket
        get :review_parsed_products
        post :confirm_parsed_products
      end
    end
  end

  # suppression et création des steps pour les form de recipes/new et recipes/edit
  resources :steps, only: [:new, :destroy]

  resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get :llm_index
    end
    member do
      post :mark_as_done
      patch :toggle_favorite

    end
  end

  resources :ingredients, only: [:index]
  # resources :ingredients, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :chats, only: [:index, :create, :destroy] do
    resources :messages, only: [:create, :index, :destroy] do
      member do
        post :create_dlc
      end
    end
    collection do
      post :create_chat_dlc
    end
  end

  get "/pages/dashboard", to: "pages#dashboard"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients_recipes, dependent: :destroy
  has_many :completions, dependent: :destroy
  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :all_blank

VALID_CATEGORIES = [
  'French',
  'Italian',
  'Japanese',
  'Mexican',
  'Indian',
  'Chinese',
  'Thai',
  'Greek',
  'Spanish',
  'Moroccan',
  'American',
  'Vietnamese',
  'Lebanese',
  'Korean',
  'Turkish'
]


  has_one_attached :photo
  validates :name, presence: true
  validates :description, presence: true
  validates :duration, presence: true
  # validates :category, presence: true, inclusion: { in: VALID_CATEGORIES }
  validates :rating, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 5,
    allow_nil: true
  }

  def ingredient_availability_for(house)
    stock = house.house_ingredients.joins(:ingredient)
      .pluck("ingredients.name", :unit, :quantity)
      .each_with_object({}) do |(name, unit, quantity), hash|
        hash[[name.downcase.strip, unit.downcase.strip]] = quantity
      end
    self.ingredients_recipes.map do |recipe_ingredient|
      key = [recipe_ingredient.name.downcase.strip, recipe_ingredient.unit.downcase.strip]
      stock_quantity = stock[key]
      {
        name: recipe_ingredient.name,
        ok: (stock_quantity && stock_quantity >= recipe_ingredient.quantity) ? true : false,
        # ok:
        quantity: recipe_ingredient.quantity,
        unit: recipe_ingredient.unit
      }
    end
  end
  def ingredients_fully_available_for?(house)
    stock = house.house_ingredients.joins(:ingredient)
      .pluck("ingredients.name", :unit, :quantity)
      .each_with_object({}) do |(name, unit, quantity), hash|
        hash[[name.downcase.strip, unit.downcase.strip]] = quantity
      end

    self.ingredients_recipes.all? do |recipe_ingredient|
      key = [
        recipe_ingredient.name.downcase.strip,
        recipe_ingredient.unit.downcase.strip
      ]
      stock_quantity = stock[key]
      stock_quantity && stock_quantity >= recipe_ingredient.quantity
    end
  end

  def decrement_house_ingredients!(house)
    # On utilise la méthode existante pour récupérer l'état de disponibilité des ingrédients
    availability = ingredient_availability_for(house)

    availability.each do |item|
      name = item[:name].downcase.strip
      quantity_needed = item[:quantity]
      unit = self.ingredients_recipes.find { |ri| ri.name.downcase.strip == name }.unit.downcase.strip

      # house_ingredient = house.house_ingredients.joins(:ingredient)
        # .find_by("LOWER(ingredients.name) = ? AND LOWER(house_ingredients.unit) = ?", name, unit)
      ingredient = Ingredient.find_by(name: name)
      house_ingredient = house.house_ingredients.find_by(ingredient: ingredient)
      next unless house_ingredient # L'ingrédient n'existe pas dans la maison, on passe
      if item[:ok]
        # Si on a assez, on décrémente
        house_ingredient.quantity -= quantity_needed
      else
        # Pas assez : on met à zéro
        house_ingredient.quantity = 0
      end
      house_ingredient.save!
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before_action :set_recipe, only: [:show, :destroy, :edit, :update, :new]

  def index
    @my_recipes = Recipe.where(user_id: current_user, my_recipe: true)
    @favorite_recipes = Recipe.where(favorite: true)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.steps.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    @recipe.my_recipe = true
    counter = 1
    if @recipe.save
      number_of_ingredients = @recipe.number_of_ingredients
      number_of_ingredients.times do
        IngredientsRecipe.create(
          recipe_id: @recipe.id,
          name: params["ingredient_name#{counter}"],
          quantity: params["ingredient_quantity#{counter}"],
          unit: params["ingredient_unit#{counter}"]
        )
        counter += 1
        puts "counter: #{counter}"
      end
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      Completion.create(recipe: @recipe)
      # soustraire les ingredients de ma recette (leur quantité)
      # à ceux que j'ai dans mon frigo
      redirect_to recipe_path
    else
      render :edit
    end
  end

    # /:recipe_id
  def update_favorite
    raise
    # je récupère mon instance de recipe
    @recipe = Recipe.find(params[:id])

    # instance.update(favorite: !instance.favorite)
    @recipe.update(favorite: @recipe.favorite)

    # si .favorite == false => je l'update en true
    # si .favorite == true => je l'update en false
    if @recipe.favorite == false
      @recipe.update(favorite: true)
    else
      @recipe == true
      @recipe.update(favorite: false)
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipe_path, status: :see_other
  end

  def mark_as_done
    @recipe = Recipe.find(params[:id])
    @recipe.decrement_house_ingredients!(@house)

    flash[:notice] = "Recette effectuée avec succès 🎉"
    redirect_to recipe_path(@recipe)

  end

    def llm_index
    # Affiche uniquement les recettes IA créées pour l'utilisateur courant
    @llm_recipes = Recipe.where(user_id: current_user, my_recipe: false)
  end
end

 private


  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :photo, :description, :category, :duration, :favorite, :rating, :number_of_ingredients, steps_attributes: [:id, :description])
  end

  def ingredients_recipe
    params.require(:ingredients_recipe).permit(:name, :quantity, :unit)
  end

app/views/recipes/edit.html.erb
<%= render partial: "shared/top_nav", locals: { return_url: recipe_path(@recipe), fav_display: false, edit_display: false, add_display: false, add_ingredient: false, fav_robot: false } %>

<div class="form-background"></div>
  <div class="container" style="margin-bottom: 5rem;">

      <div class="text-center">
        <h1>Edit my recipe</h1>
      </div>

    <div class="card shadow-sm">
      <div class="container my-1">
        <%= simple_form_for @recipe, html: { multipart: true } do |f| %>
          <div class="mb-3 mt-4">
            <%= f.input :photo, as: :file, label_html: { class: "fw-bold" } %>
          </div>

          <div class="mb-3">
            <%= f.input :name, label: "Name of the recipe:", label_html: { class: "fw-bold" } %>
          </div>

          <div class="mb-3">
            <%= f.input :rating, label: "Rating:", label_html: { class: "fw-bold" }, collection: (0..5).to_a %>
          </div>

          <div class="mb-3">
            <%= f.input :duration, label: "Duration:", label_html: { class: "fw-bold" } %>
          </div>
        </div>
      </div>

        <div class="card mt-4 p-3 shadow-sm">
          <div>
            <%= f.input :category, as: :select, label: "Category:", label_html: { class: "fw-bold" }, collection: Recipe::VALID_CATEGORIES, include_blank: "Select a category", input_html: { class: "form-control rounded-4" } %>
          </div>

          <div class="mb-3">
            <%= f.input :description, label: "Describe shortly your recipe:", label_html: { class: "fw-bold" } %>
          </div>


          <p><strong>Ingredients:</strong></p>
            <% @recipe.ingredients_recipes.each do |ingredient| %>
              <div class="row d-flex justify-content-between mb-3" data-controller= "ingredients" data-ingredients-target="row">
                <div class="ingredient-row mb-2" data-ingredients-target="remove">
                  <div class="col-4">
                    <%= text_field_tag "ingredients[][name]", ingredient.name, placeholder: "Ingredient", class: "form-control" %>
                  </div>

                  <div class="col-3">
                    <input type="text" name="ingredients[][quantity]" value="<%= ingredient.quantity %>" class="form-control" />
                  </div>

                  <div class="col-3">
                    <select name="ingredients[][unit]" class="form-control">
                      <%= options_for_select(['g', 'l', 'pc(s)'], ingredient.unit) %>
                    </select>
                  </div>

                  <div class="col-1 ms-auto p-0 d-flex justify-content-center" >
                    <button data-ingredients-target= "button" data-action= "click->ingredients#addIngredients" type="button" class="btn btn-primary">+</button>
                  </div>

                </div>
              </div>
            <% end %>
          </div>

        <div class="card mt-4 p-3 shadow-sm">
          <section>
            <h5>Steps of the recipe</h5>
            <div class="d-flex" style="gap: 5px;">
              <div id="steps" class="flex-fill">
                <%= render @recipe.steps %>
              </div>
              <%= link_to new_step_path, data: { turbo_stream: true }, class: "btn btn-primary d-flex align-self-end", style: "height: 38px;" do %>
                +
              <% end %>
            </div>
          </section>
      </div>

        <div class="text-center mt-5">
          <%= f.button :submit, "Update recipe", class: "btn btn-primary btn-xl" %>
        </div>
      <% end %>

  </div>

app/views/recipes/index.html.erb
  <%= render partial: "shared/top_nav", locals: { return_url: root_path, fav_robot: true, fav_display: false, edit_display: false, add_display: true, add_ingredient: false } %>
<div class="bandeau_top_ingr"></div>

<div class="container my-1" style="padding-bottom: 7rem;">

  <h1 class="text-center pt-2 mb-5">List of my recipes</h1>


  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    <% @my_recipes.each do |recipe| %>

      <div class="col">
        <%= link_to recipe_path(recipe), class: "card h-100 shadow-sm text-decoration-none" do %>
          <div class="card h-100 shadow-sm">
            <div class="card-product-light">
              <%= cl_image_tag recipe.photo.key, id: "pic" if recipe.photo.attached? %>

              <div class="card-description justify-content-center pt-3 px-2">
                <h5 class="ms-2"><%= recipe.name %></h5>
                <% if recipe.description.present? %>
                  <p class="ms-2 pt-2"><%= truncate(recipe.description, length: 100) %></p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/llm_index.html.erb
<%= render partial: "shared/top_nav", class: "border border-5 border-secondary", locals: { return_url: root_path, fav_display: false, edit_display: false, add_display: true, add_ingredient: false, fav_robot: false } %>
<div class="bandeau_top_ingr_dark"></div>

<div class="container my-1 ">
  <h1 class="text-center mb-5 mt-4 text-secondary">My assistant recipes</h1>

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4" style="margin-bottom: 100px;">
    <% @llm_recipes.each do |recipe| %>

      <div class="col">
        <%= link_to recipe_path(recipe), class: "card h-100 shadow-sm text-decoration-none" do %>
          <div class="card h-100 shadow-sm text-secondary">
            <div class="card-product-dark">
              <%= cl_image_tag recipe.photo.key, id: "pic" if recipe.photo.attached? %>
              <div class="card-description justify-content-center pt-3 px-2">
                <h5 class="ms-2"><%= recipe.name %></h5>
                <% if recipe.description.present? %>
                  <p class="ms-2 pt-2"><%= truncate(recipe.description, length: 100) %></p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render partial: "shared/top_nav", locals: { return_url: recipes_path, fav_display: false, fav_robot: false, edit_display: false, add_display: false, add_ingredient: false } %>


<div class="container my-1">
  <%= simple_form_for @recipe, html: { multipart: true } do |f| %>
    <div class="mb-3 mt-4">
      <%= f.input :photo, as: :file %>
    </div>

    <div class="mb-3">
      <%= f.input :name, label: "Name of the recipe" %>
    </div>

    <div class="category-selector mb-3">
      <%= f.input :category, as: :radio_buttons, label: "Category", collection: Recipe::VALID_CATEGORIES %>
    </div>

    <div class="mb-3">
      <%= f.input :description, label: "Describe shortly your recipe" %>
    </div>

    <div class="mb-3">
      <%= f.input :rating, label: "Rating" %>
    </div>

    <!--- Afin de pouvoir rajouter des ingrédients a la liste, il faut d'abord préciser le nombre d'ingrédients, ici entre 1 et 20
      ---- Stimulus JS -->
    <div class="row d-flex justify-content-between mb-3" data-controller= "ingredients" data-ingredients-target="row">
      <div>
        <%= f.input :number_of_ingredients, collection: 1..20, placeholder: "number of ingredients" %>
      </div>

      <div class="ingredient-row mb-2" data-ingredients-target="remove">
        <div class="col-4">
          <%= text_field_tag :ingredient_name1, nil, placeholder: "Ingredients", class: "form-control" %>
        </div>

        <div class="col-3">
          <%= text_field_tag :ingredient_quantity1, nil, placeholder: "Quantity", class: "form-control" %>
        </div>

        <div class="col-3">
          <%= select_tag :ingredient_unit1, options_for_select(['g', 'l', 'pc(s)']), class: "form-select" %>
        </div>

        <div class="col-1 ms-auto p-0 d-flex justify-content-center">
          <button data-ingredients-target= "button" data-action= "click->ingredients#addIngredients" type="button" class="btn btn-primary">+</button>
          <button data-ingredients-target= "delete" data-action= "click->ingredients#removeRow" type="button" class="trash"><i class="fa-solid fa-trash"></i></button>
        </div>
      </div>
    </div>

    <div class="mb-3">
      <%= f.input :duration, label: "Duration" %>
    </div>

    <section>
      <h5>Steps of the recipe</h5>
      <div class="d-flex" style="gap: 5px;">
        <div id="steps" class="flex-fill">
          <%= render @recipe.steps %>
        </div>
        <%= link_to new_step_path, data: { turbo_stream: true }, class: "btn btn-primary d-flex align-self-end", style: "height: 38px;" do %>
          +
        <% end %>
      </div>
    </section>

    <div class="text-center my-4">
      <%= f.button :submit, "Create recipe", class: "btn btn-primary btn-xl" %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= render partial: "shared/top_nav", locals: { return_url: recipes_path, fav_display: false, edit_display: true, add_display: false, add_ingredient: false, fav_robot: false } %>



<div class="container">

<h1 class="text-center"><%= @recipe.name %></h1>

  <div class="container-img mt-4">
    <%= cl_image_tag @recipe.photo.key, class: "picture" if @recipe.photo.attached? %>
  </div>

    <%#  <%= if message.recipe.favorite? %>
      <%# <%= image_tag "fav-light.png", alt: "return", width: 40, height: 40, class: "rounded-circle" %>
    <%# <%= else %>
      <%# <%= image_tag "fav.png", alt: "return", width: 40, height: 40, class: "rounded-circle" %>
    <%# end %>
  <%# <ul class="list-group list-group-flush"> %>

  <div class="mt-3 row row-cols-2 g-2">
    <div class="col">
        <div class="card-recipe h-100">

          <div class="text-center pt-3 pb-2">
            <strong>Category:</strong>
              <p><%= @recipe.category %></p>
            <strong>Duration:</strong>
              <p><%= @recipe.duration %></p>
          </div>

        </div>
      </div>

    <div class="col">
      <div class="card-recipe">
        <div class="text-center pt-4" style="padding-bottom: 3.5rem;">
            <strong>Rating:</strong>
            <p class="mt-2"><% rating = @recipe.rating.to_i %>
            <% 5.times do |i| %>
              <% if i < rating %>
                <i class="fas fa-star text-warning"></i>
              <% else %>
                <i class="far fa-star text-muted"></i>
              <% end %>
            <% end %>
            </p>
        </div>
      </div>
    </div>

  </div>

    <div class="card-recipe mt-2 w-100">
      <div class="text-center pt-3">
        <p><strong>Ingredients:</strong></p>
      </div>

        <div class="text-start p-3">
          <% @recipe.ingredient_availability_for(@house).each do |ingredient| %>
            <li class="mb-1">
              <span class="badge <%= ingredient[:ok] ? 'bg-success' : 'bg-danger' %>">
                <%= ingredient[:ok] ? 'availble' : 'Missing' %>
              </span>
              <strong><%= ingredient[:name] %></strong> :
              <%= ingredient[:quantity] %> <%= ingredient[:unit] %>
            </li>
          <% end %>
        </div>



    </div>

    <div class="card-recipe mt-2 pt-4 px-2">
      <ul><strong>Steps:</strong>
        <ol>
          <% @recipe.steps.each do |step| %>
            <li><%= step.description %></li><br>
          <% end %>
        </ol>
      </ul>
    </div>


  <div style="margin-bottom: 100px;">

    <div class="d-flex justify-content-between">

      <div class="mx-auto">
        <%= link_to "Mark as done", house_house_ingredients_path(@house), method: :post, class:"btn btn-primary text-secondary" %>
      </div>

      <%= link_to recipe_path(@recipe), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"} do %>
      <%= image_tag "icons/trash-icon.png", alt:"trash", style:"height: 35px; width: 35px;" %>
      <% end %>
      </div>

  </div>



      <%# <div class="col text-align-end">
        <%= link_to recipe_path(@recipe), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"} do %>
        <%# <i class="fa-solid fa-trash"></i> %>
        <%# <% end %>
      <%# </div> %>
</div>