config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  root to: "home#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :home, only: [:index]

  resources :pages, only: [:index, :show, :new, :create, :edit, :update] do

  end
  resources :houses, only: [:index, :show, :new, :create, :edit, :update] do
    resources :house_ingredients do
      collection do
        #ajout de cet élément pour crééer une route path
        post :analyze_ticket
        get :review_parsed_products
        post :confirm_parsed_products
      end
    end
  end

  # suppression et création des steps pour les form de recipes/new et recipes/edit
  resources :steps, only: [:new, :destroy]

  resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get :llm_index
    end
    member do
      post :mark_as_done
      patch :toggle_favorite

    end
  end

  resources :ingredients, only: [:index]
  # resources :ingredients, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :chats, only: [:index, :create, :destroy] do
    resources :messages, only: [:create, :index, :destroy] do
      member do
        post :create_dlc
      end
    end
    collection do
      post :create_chat_dlc
    end
  end

  get "/pages/dashboard", to: "pages#dashboard"
end

app/views/shared/_flashes.html.erb
<!--

<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>


-->

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_mobile_navbar.html.erb
<!-- filepath: /Users/fabienhoarau/code/robagcoto/shelfie-proto/app/views/shared/_mobile_navbar.html.erb -->
<div class="position-fixed bottom-0 start-0 w-100" style="z-index: 2000;">
  <div class="blur-background-mobile"></div>

  <div class="navbar-mobile positioned d-md-none shadow">
    <div class="d-flex justify-content-around align-items-center px-3 py-1 gap-3" style="height: 60px;">

      <%= link_to root_path do %>
        <% if current_page?(root_path) %>
          <%= image_tag "picto_navbar/picto-home.png", alt: "home", style: "height:40px;" %>
        <% else %>
          <%= image_tag "picto_navbar/picto_navbar_home.png", alt: "home", style: "height:40px;" %>
        <% end %>
      <% end %>

      <%= link_to house_house_ingredients_path(@house) do %>
        <% if current_page?(house_house_ingredients_path(@house)) %>
          <%= image_tag "picto_navbar/picto-ingr.png", alt: "return", style: "height:40px;" %>
        <% else %>
          <%= image_tag "picto_navbar/picto_navbar_ingr.png", alt: "return", style: "height:40px;" %>
        <% end %>
      <% end %>

      <%= link_to "#", data: { bs_toggle: "modal", bs_target: "#ticketModal" } do %>
        <%= image_tag "picto_navbar/picto_navbar_picture.png", alt: "picture", style: "height:40px;" %>
      <% end %>

      <%= link_to recipes_path do %>
        <% if current_page?(recipes_path) %>
          <%= image_tag "picto_navbar/picto-recipe.png", alt: "recipes", style: "height:40px;" %>
        <% else %>
          <%= image_tag "picto_navbar/picto_navbar_recipes.png", alt: "recipes", style: "height:40px;" %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

<div class="modal fade" id="ticketModal" tabindex="-1" aria-labelledby="ticketModalLabel" aria-hidden="true";>
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content align-items-center">

      <div class="modal-header">
        <h1 class="modal-title fs-5" id="ticketModalLabel">Scan a Ticket</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <%= form_with url: analyze_ticket_house_house_ingredients_path(@house), local: true, html: { multipart: true } do |f| %>
          <div class="mb-3">
            <%= f.label :ticket_photo, "Upload or take a photo of your ticket", class: "form-label" %>
            <%= f.file_field :ticket_photo, accept: 'image/*', capture: 'environment', class: "form-control" %>
          </div>
          <div class="modal-footer d-flex justify-content-center">
            <%= f.submit "Scan ticket", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <%= image_tag "logo-shelfie-ai-02.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", new_chat_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "icon_user.png", class: "avatar", alt: "dropdown menu" %>
            <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_redirect.turbo_stream.erb
<turbo-stream action="replace" target="shopping_list_form">
  <template>
    <script>
      window.location.href = "<%= url %>";
    </script>
  </template>
</turbo-stream>

app/views/shared/_top_nav.html.erb
<div class="d-flex justify-content-between text-center m-3 position-relative"
     style="z-index: 1100;">
  <%= link_to return_url do %>
    <%= image_tag "return.png", alt: "return", class: "return-btn" %>
  <% end %>

  <% if fav_display %>
    <%= link_to pages_dashboard_path do %>
      <%= image_tag "fav.png", alt: "fav", class: "fav-btn" %>
    <% end %>
  <% end %>

  <% if fav_robot %>
    <%= link_to llm_index_recipes_path do %>
      <%= image_tag "shelfie-robot2.png", alt: "robot", class:"fav-btn" %>
    <% end %>
  <% end %>

  <% if edit_display %>
    <%= link_to edit_recipe_path(@recipe), data: { turbo: false } do %>
      <%= image_tag "edit.png", alt:"edit", class:"edit-btn" %>
    <% end %>
  <% end %>

  <% if add_display %>
    <%= link_to new_recipe_path do %>
      <%= image_tag "close.png", alt: "add", class: "add-btn" %>
    <% end %>
  <% end %>

  <% if add_ingredient %>
    <%= link_to new_house_house_ingredient_path(@house) do %>
      <%= image_tag "close.png", alt: "add", class: "add-btn" %>
    <% end %>
  <% end %>
</div>